spring:
  application:
    name: cs-logger-service
  kafka:
    bootstrap-servers: ${KAFKA1_BOOTSTRAP_SERVICE_URL},${KAFKA2_BOOTSTRAP_SERVICE_URL},${KAFKA3_BOOTSTRAP_SERVICE_URL}
    consumer:
      properties:
        session:
          timeout:
            ms: 60000
        reconnect:
          backoff:
            ms: 1000
            max:
              ms: 20000

database:
  host: ${LS_DB_HOST}
  port: ${LS_DB_PORT}
  name: ${LS_DB_NAME}
  username: ${LS_DB_USER}
  password: ${LS_DB_PASSWORD}
  schema: ${LS_DB_SCHEMA}

server:
  port: ${SERVER_INTERNAL_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true